# Intrinsically, pods are not exposed to the internet.
# Pods needs something to help expose them to the browser/internet.
# These are called services.
# After the service to expose them has been created, the pod can be accessed via
# localhost:<nodePort>    Since we are using docker desktop, it is safe to use "localhost"
# If we are not using docker desktop, we will need to issue command: $minikube ip to get the domain IP.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  # minReadySeconds: 30
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template: # template for the pods
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5-multi
--- # This is a document separator for yaml files
apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    app: queue
spec:
  containers:
    - name: queue
      image: richardchesterwood/k8s-fleetman-queue:release1-multi
